# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conversation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63onversation.proto\x12\x06traini\"\x07\n\x05\x45mpty\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"\x84\x01\n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12#\n\x06\x66ormat\x18\x02 \x01(\x0b\x32\x13.traini.AudioFormat\x12\x17\n\x0fsequence_number\x18\x03 \x01(\x03\x12$\n\ttimestamp\x18\x04 \x01(\x0b\x32\x11.traini.Timestamp\"Y\n\x0b\x41udioFormat\x12\x13\n\x0bsample_rate\x18\x01 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x02 \x01(\x05\x12\x11\n\tbit_depth\x18\x03 \x01(\x05\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\"\x9f\x01\n\x11\x43onversationEvent\x12+\n\x0c\x61udio_output\x18\x01 \x01(\x0b\x32\x13.traini.AudioOutputH\x00\x12/\n\x0e\x61udio_complete\x18\x02 \x01(\x0b\x32\x15.traini.AudioCompleteH\x00\x12#\n\x05\x65rror\x18\x64 \x01(\x0b\x32\x12.traini.ErrorEventH\x00\x42\x07\n\x05\x65vent\":\n\x0b\x41udioOutput\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x03\"%\n\rAudioComplete\x12\x14\n\x0ctotal_chunks\x18\x01 \x01(\x03\"+\n\nErrorEvent\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\x16\x45ndConversationRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"$\n\x0eSessionSummary\x12\x12\n\nsession_id\x18\x01 \x01(\t2\xa9\x01\n\x13\x43onversationService\x12G\n\x12StreamConversation\x12\x12.traini.AudioChunk\x1a\x19.traini.ConversationEvent(\x01\x30\x01\x12I\n\x0f\x45ndConversation\x12\x1e.traini.EndConversationRequest\x1a\x16.traini.SessionSummaryb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conversation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=30
  _EMPTY._serialized_end=37
  _TIMESTAMP._serialized_start=39
  _TIMESTAMP._serialized_end=82
  _AUDIOCHUNK._serialized_start=85
  _AUDIOCHUNK._serialized_end=217
  _AUDIOFORMAT._serialized_start=219
  _AUDIOFORMAT._serialized_end=308
  _CONVERSATIONEVENT._serialized_start=311
  _CONVERSATIONEVENT._serialized_end=470
  _AUDIOOUTPUT._serialized_start=472
  _AUDIOOUTPUT._serialized_end=530
  _AUDIOCOMPLETE._serialized_start=532
  _AUDIOCOMPLETE._serialized_end=569
  _ERROREVENT._serialized_start=571
  _ERROREVENT._serialized_end=614
  _ENDCONVERSATIONREQUEST._serialized_start=616
  _ENDCONVERSATIONREQUEST._serialized_end=660
  _SESSIONSUMMARY._serialized_start=662
  _SESSIONSUMMARY._serialized_end=698
  _CONVERSATIONSERVICE._serialized_start=701
  _CONVERSATIONSERVICE._serialized_end=870
# @@protoc_insertion_point(module_scope)
