# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: traini.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'traini.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctraini.proto\x12\x06traini\"?\n\x11HumanToDogRequest\x12\x14\n\x0c\x61udio_base64\x18\x01 \x01(\t\x12\x14\n\x0c\x61udio_format\x18\x02 \x01(\t\"O\n\x12HumanToDogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x11\n\taudio_url\x18\x03 \x01(\t2]\n\rTrainiService\x12L\n\x13TranslateHumanToDog\x12\x19.traini.HumanToDogRequest\x1a\x1a.traini.HumanToDogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'traini_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HUMANTODOGREQUEST']._serialized_start=24
  _globals['_HUMANTODOGREQUEST']._serialized_end=87
  _globals['_HUMANTODOGRESPONSE']._serialized_start=89
  _globals['_HUMANTODOGRESPONSE']._serialized_end=168
  _globals['_TRAINISERVICE']._serialized_start=170
  _globals['_TRAINISERVICE']._serialized_end=263
# @@protoc_insertion_point(module_scope)
